# Generated by Django 2.2.16 on 2022-05-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20220524_1833'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique appversion',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='author',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique appversion'),
        ),
    ]
